pipelines:
  default:
    - step:
        name: test in python 3.6
        image: python:3.6
        caches:
          - pip
        script:
          - pip install -r requirements.txt
          - python -m download_java_release.cli
    - step:
        name: test in python 2.7
        image: python:2.7
        caches:
          - pip
        script:
          - pip install -r requirements.txt
          - python -m download_java_release.cli
